/* Configuration for functional generated by Alire */
#ifndef FUNCTIONAL_CONFIG_H
#define FUNCTIONAL_CONFIG_H

#define CRATE_VERSION "2.3.0"
#define CRATE_NAME "functional"

#define ALIRE_HOST_OS "macos"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "homebrew"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#endif
