// ============================================================================
// File: software_test_guide.typ
// Purpose: Software Test Guide for the Functional library.
// Scope: Project-specific STG content plus invocation of shared formal-document
//   functionality from core.typ.
// Usage: This is an authoritative Typst source document. The generated PDF is
//   the distribution artifact.
// Modification Policy:
//   - Edit this file for project-specific STG content.
//   - Keep shared presentation logic in core.typ.
// Table Ordering:
//   Sort any table whose rows a reader might scan to locate a specific
//   entry — definitions, acronyms, constraints, packages, interfaces,
//   and similar reference tables.  Sort alphabetically by the first
//   column.  Tables with an inherent sequence (requirement IDs within
//   a section, change history, workflow steps) retain their logical order.
// SPDX-License-Identifier: BSD-3-Clause
// ============================================================================

#import "core.typ": formal_doc

#let doc = (
  title: "Software Test Guide",
  project_name: "FUNCTIONAL",
  authors: ("Michael Gardner",),
  version: "4.1.0",
  status: "Released",
  status_date: "2026-04-27",
  spdx_license: "BSD-3-Clause",
  license_file: "See the LICENSE file in the project root",
  copyright: "© 2026 Michael Gardner, A Bit of Help, Inc.",
  applies_to: "^4.1",
)

#let profile = (
  variant: "library",
  library_role: "utility",
  app_role: none,
  assurance: "spark-targeted",
  execution: "sequential",
  parallelism: "none",
  platform: ("desktop", "server", "embedded"),
  execution_environment: ("linux", "macos", "windows", "ada-runtime"),
  processor_architecture: ("amd64", "arm64", "arm32"),
  deployment: "native",
)

#let change_history = (
  (
    version: "4.1.0",
    date: "2025-12-18",
    author: "Michael Gardner",
    changes: "Add test warning suppressions; migrate to Typst format.",
  ),
  (
    version: "4.0.0",
    date: "2025-12-12",
    author: "Michael Gardner",
    changes: "Add Map_To_Result and Map_To_Result_With_Param tests.",
  ),
  (
    version: "3.0.0",
    date: "2025-11-30",
    author: "Michael Gardner",
    changes: "Initial test framework.",
  ),
)

#show: formal_doc.with(doc, profile, change_history)

= Introduction

== Purpose

This Software Test Guide (STG) describes the testing strategy, test organization, execution procedures, and maintenance guidance for the *Functional* library.

== Scope

This document covers:
- test categories and their purposes,
- test directory structure and naming conventions,
- test framework usage,
- test execution commands,
- traceability between requirements and tests, and
- guidelines for writing new tests.

== References

- Software Requirements Specification (SRS).
- Software Design Specification (SDS).

= Test Strategy

== Test Categories

#table(
  columns: (auto, auto, 1fr, auto),
  table.header([*Category*], [*Location*], [*Purpose*], [*Target*]),
  [Unit Tests], [`test/unit/`], [Test individual packages in isolation.], [≥ 90% coverage],
  [SPARK Tests], [`test/spark/`], [Verify SPARK-compatible instantiations.], [100% legality],
  [Integration Tests], [`test/integration/`], [Cross-package workflows.], [Key workflows],
)

See CHANGELOG for current test counts per release.

== Testing Philosophy

- *Test behavior, not implementation* — tests verify observable behavior.
- *One assertion per concept* — each test validates one logical concept.
- *Descriptive names* — test names describe what is being tested.
- *No mocking core types* — Result, Option, Either are tested directly.
- *SPARK verification* — domain types are verified with GNATprove.

= Test Organization

== Directory Structure

```text
test/
├── common/                          # Shared test infrastructure
│   ├── test_framework.ads           # Framework spec
│   └── test_framework.adb           # Framework impl
├── config/                          # Test configuration
│   └── functional_tests_config.ads  # Auto-generated by Alire
├── unit/                            # Unit test suites
│   ├── test_result.adb              # Result tests
│   ├── test_option.adb              # Option tests
│   ├── test_either.adb              # Either tests
│   ├── test_try.adb                 # Try tests
│   ├── test_try_option.adb          # Try Option tests
│   ├── test_try_map_to_result.adb   # Map_To_Result tests
│   ├── test_try_map_to_result_with_param.adb
│   ├── test_scoped.adb              # Scoped tests
│   └── unit_runner.adb              # Unit test runner
├── spark/                           # SPARK verification tests
│   ├── spark_instantiations.ads     # SPARK-compatible instantiations
│   └── spark_instantiations.adb
├── functional_test.gpr              # Test GPR project
└── alire/                           # Alire dependencies (generated)
```

== Naming Conventions

// Sort rows alphabetically by the first column.
#table(
  columns: (auto, auto, 1fr),
  table.header([*Element*], [*Convention*], [*Example*]),
  [Runner], [`unit_runner.adb`], [`unit_runner.adb`],
  [Test file], [`test_<module>.adb`], [`test_result.adb`],
  [Test package], [`Test_<Module>`], [`Test_Result`],
  [Test procedure], [`Test_<Operation>_<Scenario>`], [`Test_Map_Success`],
)

== Build/Test Projects

#table(
  columns: (auto, 1fr),
  table.header([*Project*], [*Purpose*]),
  [`functional_test.gpr`], [Builds all test executables; extends `functional.gpr`.],
)

= Test Framework

== Framework Overview

The Functional library uses a lightweight custom test framework (`test/common/test_framework.ads`).

== Framework API

```ada
package Test_Framework is
   procedure Register_Results
     (Suite_Name   : String;
      Test_Count   : Natural;
      Passed_Count : Natural);

   function All_Passed return Boolean;

   procedure Report_And_Exit;
end Test_Framework;
```

== Usage Pattern

```ada
with Test_Framework;

procedure Test_My_Module is
   Test_Count   : Natural := 0;
   Passed_Count : Natural := 0;

   procedure Assert (Condition : Boolean; Name : String) is
   begin
      Test_Count := Test_Count + 1;
      if Condition then
         Passed_Count := Passed_Count + 1;
         Put_Line ("[PASS] " & Name);
      else
         Put_Line ("[FAIL] " & Name);
      end if;
   end Assert;

begin
   Assert (Is_Ok (Result), "Ok creates success");

   Test_Framework.Register_Results
     ("My_Module", Test_Count, Passed_Count);
end Test_My_Module;
```

= Test Execution

== Running All Tests

```bash
make test-all
```

Or manually:

```bash
alr build
./bin/test/unit_runner
```

== Running Specific Suites

```bash
# Run individual test
./bin/test/test_result

# Run unit tests only
make test-unit
```

== Expected Output

```text
========================================
Test Summary: Functional.Result
========================================
Total tests: 84
Passed: 84
Failed: 0
========================================
All tests passed!
```

== SPARK Verification

```bash
# Run SPARK proof
make spark-prove

# Run SPARK legality check only
make spark-check
```

= Test Details

== Unit Tests

=== Result Tests (`test_result.adb`)

Tests all Result operations: constructors (Ok, Error), queries (Is_Ok, Is_Error, Value, Get_Error), transformations (Map, Map_Error, And_Then, Or_Else), and extraction (Unwrap_Or, Match).

=== Option Tests (`test_option.adb`)

Tests all Option operations: constructors (Some, None), queries (Is_Some, Is_None, Value), transformations (Map, And_Then, Or_Else, Filter), and extraction (Unwrap_Or, Match).

=== Either Tests (`test_either.adb`)

Tests all Either operations: constructors (Left, Right), queries (Is_Left, Is_Right, Left_Value, Right_Value), and transformations (Map_Left, Map_Right, Fold).

=== Try Tests (`test_try.adb`, `test_try_option.adb`, `test_try_map_to_result.adb`)

Tests exception bridging: success path (no exception), exception path (caught), exception mapping (correct error kind), and default error kind (unmapped exceptions).

=== Scoped Tests (`test_scoped.adb`)

Tests RAII guards: normal cleanup path, exception in guarded block, and exception in Release (suppressed).

== SPARK Tests

=== SPARK Instantiations (`spark_instantiations.ads`)

Verifies that Result, Option, and Either can be instantiated under SPARK_Mode On:

```ada
pragma SPARK_Mode (On);

package SPARK_Instantiations is
   type Error_Kind is (E1, E2);

   package Int_Result is new Functional.Result (Integer, Error_Kind);
   package Int_Option is new Functional.Option (Integer);
end SPARK_Instantiations;
```

= Writing New Tests

== Test Template

```ada
pragma Ada_2022;
--  ======================================================================
--  Test_New_Feature
--  ======================================================================
--  Copyright (c) 2025 Michael Gardner, A Bit of Help, Inc.
--  SPDX-License-Identifier: BSD-3-Clause
--  Purpose: Unit tests for New_Feature.
--  ======================================================================

with Ada.Text_IO;    use Ada.Text_IO;
with Ada.Command_Line;
with Functional.New_Feature;
with Test_Framework;

procedure Test_New_Feature is
   Test_Count   : Natural := 0;
   Passed_Count : Natural := 0;

   procedure Assert (Condition : Boolean; Test_Name : String) is
   begin
      Test_Count := Test_Count + 1;
      if Condition then
         Passed_Count := Passed_Count + 1;
         Put_Line ("[PASS] " & Test_Name);
      else
         Put_Line ("[FAIL] " & Test_Name);
      end if;
   end Assert;

begin
   --  Tests here

   Test_Framework.Register_Results
     ("New_Feature", Test_Count, Passed_Count);

   if Passed_Count = Test_Count then
      Ada.Command_Line.Set_Exit_Status (Ada.Command_Line.Success);
   else
      Ada.Command_Line.Set_Exit_Status (Ada.Command_Line.Failure);
   end if;
end Test_New_Feature;
```

== Adding to Build Configuration

Add new test to `functional_test.gpr`:

```ada
for Main use (
   "unit_runner.adb",
   "test_new_feature.adb"  --  Add new test
);
```

== Test Doubles / Mock Patterns

Mocking is generally not needed for Functional library tests:
- Core types are pure (no I/O).
- Try tests use controlled exceptions.
- Scoped tests use test resources.

= Traceability

== Requirements to Tests

#table(
  columns: (auto, 1fr),
  table.header([*Requirement*], [*Test Coverage*]),
  [FR-R01..R12], [`test_result.adb` — constructors, queries, transformations, extraction],
  [FR-O01..O10], [`test_option.adb` — constructors, queries, transformations, extraction],
  [FR-E01..E08], [`test_either.adb` — constructors, queries, transformations],
  [FR-T01..T07], [`test_try.adb`, `test_try_map_to_result.adb`, `test_try_map_to_result_with_param.adb`],
  [FR-S01..S04], [`test_scoped.adb` — guard lifecycle, exception suppression],
  [NFR-07], [`spark_instantiations.ads` — SPARK legality verification],
)

== Layer Coverage

#table(
  columns: (auto, 1fr),
  table.header([*Module Family*], [*Representative Test Areas*]),
  [Core Types (SPARK)], [`test_result.adb`, `test_option.adb`, `test_either.adb`, `spark_instantiations.ads`],
  [Exception Bridges], [`test_try.adb`, `test_try_option.adb`, `test_try_map_to_result*.adb`],
  [RAII Guards], [`test_scoped.adb`],
)

= Test Maintenance

== When to Update

- *New operation added*: add tests for the new operation.
- *Behavior changed*: update affected tests.
- *Bug fixed*: add a regression test.
- *API signature changed*: update test instantiations.

== Quality Guidelines

- Each public operation should have at least one test.
- Test both success and failure paths.
- Test edge cases (empty values, boundary conditions).
- Keep tests independent (no shared mutable state).

== Continuous Integration

Tests run automatically on:
- pull request creation,
- push to main branch, and
- release tag creation.
